---
http_interactions:
- request:
    method: get
    uri: https://api.tfl.gov.uk/Cabwise/search?app_id=TFL_APP_ID&app_key=TFL_APP_KEY&lat=bar&lon=foo
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Host:
      - api.tfl.gov.uk
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Date:
      - Fri, 11 Dec 2020 20:26:03 GMT
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '317'
      Connection:
      - keep-alive
      Set-Cookie:
      - __cfduid=d264013c6de90b520c243ff68e8cde7b31607718363; expires=Sun, 10-Jan-21
        20:26:03 GMT; path=/; domain=.tfl.gov.uk; HttpOnly; SameSite=Lax
      Cache-Control:
      - public, must-revalidate, max-age=30, s-maxage=60
      Via:
      - 1.1 varnish
      Age:
      - '0'
      Access-Control-Allow-Headers:
      - Content-Type
      Access-Control-Allow-Methods:
      - GET,POST,PUT,DELETE,OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Api-Entity-Payload:
      - Place
      X-Backend:
      - api
      X-Cache:
      - MISS
      X-Cacheable:
      - Yes. Cacheable
      X-Frame-Options:
      - deny
      X-Proxy-Connection:
      - unset
      X-Ttl:
      - '10.000'
      X-Ttl-Rule:
      - '0'
      X-Varnish:
      - '1497008637'
      X-Aspnet-Version:
      - 4.0.30319
      X-Operation:
      - Cabwise_Get
      X-Api:
      - ReleasedUnifiedAPIProd
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Request-Id:
      - 06f5147ad4000006c93b1fd000000001
      Expect-Ct:
      - max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
      Server:
      - cloudflare
      Cf-Ray:
      - 6001f03e1e1c06c9-LHR
    body:
      encoding: ASCII-8BIT
      string: '{"$type":"System.Web.Http.HttpError, System.Web.Http","message":"The
        request is invalid.","messageDetail":"The parameters dictionary contains a
        null entry for parameter ''lat'' of non-nullable type ''System.Double'' for
        method ''System.Net.Http.HttpResponseMessage Get(Double, Double, System.String,
        System.String, Double, System.String, System.Nullable`1[System.Int32], Boolean,
        Boolean, Boolean)'' in ''Tfl.Api.Presentation.PublicApi.Controllers.CabwiseController''.
        An optional parameter must be a reference type, a nullable type, or be declared
        as an optional parameter."}'
  recorded_at: Fri, 11 Dec 2020 20:26:03 GMT
recorded_with: VCR 6.0.0
